
POST http://{{url}}/api/v1/login
Content-Type: application/json

{
  "uid" : "tangthinker",
  "password" : "333"
}

###

POST http://{{url}}/api/v1/register
Content-Type: application/json

{
  "uid" : "tangthinker",
  "password" : "333"
}