
POST http://{{url}}/api/v1/login
Content-Type: application/json

{
  "uid" : "tangthinker",
  "password" : "333"
}

###

POST http://{{url}}/api/v1/register
Content-Type: application/json
X-tangthinker-secret: loveVG

{
  "uid" : "tangthinker",
  "password" : "333"
}

###

POST http://{{url}}/api/v1/modify-password
Content-Type: application/json

{
  "uid" : "tangthinker",
    "old_password" : "333",
    "new_password" : "444"
}

###
POST http://{{url}}/api/v1/uid-unique
Content-Type: application/json

{
  "uid" : "tangthinker"
}

###
POST http://{{url}}/api/v1/token-valid
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzMxMjgxMDcsImp0aSI6InRhbmd0aGlua2VyIiwiaWF0IjoxNzMzMTI4MDQ3fQ.WlgqhlxYcy7yBxzoiGB4O5oPYrDJVWRQsufAHjAvwSI"
}